# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app_bundle.event_listener.echo_module.echo_event_subscriber:
        class: AppBundle\EventListener\EchoEventSubscriber
        arguments:
            - @logger
        tags:
            - { name: kernel.event_subscriber, band: acme.queue.app_1.echo_module.echo_queue }
